### ISSUE TITLE
How can i use this

### ISSUE THREAD

**Issue by mfat** [redpilllabs/GFIGeoIP#1]
Thanks for the effort. Is there a separate list for Iran? So how can i use this in my Xray/v2ray server or clients?
For example Shadowrocket suports cidr lists, domain prefixes and geolite dayabases for optimized routing.

**Comment by 0xNeu** [comment]
> Is there a separate list for Iran?
If you're looking for a list of Iranian websites and services, this is not it, but take a look at [iran-hosted-domains](https://github.com/bootmortis/iran-hosted-domains). This repo only contains the IPs in CIDR format.

> So how can i use this in my Xray/v2ray server or clients?
Right now, this is utilized [GFIProxyProtector](https://github.com/0xNeu/GFIProxyProtector) and the [Rainb0w](https://github.com/0xNeu/Rainb0w) proxy installer script with even better protection features. You can come up with your own solutions that are IP-based.

> For example Shadowrocket suports cidr lists, domain prefixes and geolite dayabases for optimized routing.

SS and v2ray accept only the binary version (.mmdb) but the aggregated database in this repo is in the .csv format, I guess the above solutions are a better choice for this scenario.
