### ISSUE TITLE
پرسش و درخواست مهم

### ISSUE THREAD

**Issue by Graveyard9988** [redpilllabs/GFIGeoIP#2]
درود
در حال حاضر ریپو هی Chocolate4U بیشترین مخازن بای پس ip و دامین های ایرانی و خارجی رو دارن
https://github.com/Chocolate4U?tab=repositories
ایا امکانش هست که PR بزنین به ریپو های ایشون و در تکمیل دیتابیسشون کمک کنید؟

چرا که نکوباکس و هیدیفای نیز مخازن شکلات را پشتیبانی می کنند که بیشترین انعطاف و همکاری در تکمیل db ها و dat ها و srs ها (فرمت جدید جایگزین db در سینگ باکس 1.8 ( را دارند 

سپاس بیکران

**Comment by kyochikuto** [comment]
درود بر شما
اطمینان ندارم که آیا مولفین مخازن مذکور تمایلی به این مورد داشته باشند و اگر هم داشته باشند داده های این مخزن بطور متن باز در اختیارشان قرار گرفته و می‌توانند در پایگاه خود تجمیع کنند. از طرفی اکثر وبسایت های ایرانی پرکاربرد با دامنه های .ir فعالیت میکنند که توسط regex ها در هسته های کنونی به راحتی قابل مسیریابی هستند و مواردی هم که از این پسوند استفاده نمی‌کنند در حالت های  IPonDemand بواسطه ی آی‌پی بررسی شده و مسیریابی می‌شوند بنابراین طویل بودن فهرست وبسایت های بایپس نه تنها غیرضروری بوده بلکه حجم پایگاه داده ها افزایش داده و همچنین کارایی و سرعت را کاهش خواهد داد.

پیروز باشید.

**Comment by Graveyard9988** [comment]
سپاس از توضیحات جامع شما

چرا که نه، ریپو های شکلات با کمک بسیاری از کاربران دلسوزی همچون شما گرداوری شده ؛ بنابراین اگر ایده یا پیشنهادی دارید حتما در بخش ایشو یا PR ان ها مطرح کنید تا به غنای هر چه بیشتر این دیتابیس ها برسیم

سپاس دوباره
